#include "MexprEnums.h"

char *
Mexpr_get_string_token(int token_code){
    switch(token_code){
	case INVALID:
	    return "INVALID";
	case INT:
	    return "INT";
	case DOUBLE:
	    return "DOUBLE";
	case VARIABLE:
	    return "VARIABLE";
	case BRACKET_START:
	    return "BRACKET_START";
	case BRACKET_END:
	    return "BRACKET_END";
	case COMMA:
	    return "COMMA";
	case PLUS:
	    return "PLUS";
	case MINUS:
	    return "MINUS";
	case MULTIPLY:
	    return "MULTIPLY";
	case DIVIDE:
	    return "DIVIDE";
	case REMAINDER:
	    return "REMAINDER";
	case MIN:
	    return "MIN";
	case MAX:
	    return "MAX";
	case SIN:
	    return "SIN";
	case COS:
	    return "COS";
	case POW:
	    return "POW";
	case NEQ:
	    return "NEQ";
	case GREATER_THAN_OR_EQUAL_TO:
	    return "GREATER_THAN_OR_EQUAL_TO";
	case GREATER_THAN:
	    return "GREATER_THAN";
	case LESS_THAN_OR_EQUAL_TO:
	    return "LESS_THAN_OR_EQUAL_TO";
	case LESS_THAN:
	    return "LESS_THAN";
	case EQ:
	    return "MATH_EQ";
	case WHITE_SPACE:
	    return "SPACE";
	case TAB:
	    return "TAB";
	case PARSER_EOF:
	    return "PARSER_EOF";
	default:
	    return "NA";
    }
}
